matrix:
  include:
    - language: python
      python:
        - "3.7"
        - "3.8"
      before_install:
          - cd clients/python
      install:
        - pip install -r requirements.txt
      before_script:
        - cd clients/python
      env:
        - PYTHONPATH=src
      script:
        - python -m unittest discover
    - language: java
      jdk:
      - openjdk8